### PR TITLE
Cast data and timelines to native python types

### PR DESCRIPTION
**Pull request by BrianJKoopman**
Data within fields and timelines returned from `get_data()` currently return
`spt3g.core.DoubleVector`. To make it easy to work with loaded data cast these
as lists when we load the data.

### CODE REVIEW

**Comment by mhasself** [comment]
Please emit numpy arrays instead of lists.  "native" python types are not well-suited to numerical applications.

**Comment by BrianJKoopman** [comment]
Right. I was motivated by the component I was passing the resulting dictionaries into in sisock not liking the DoubleVector or np.array types, seems I won't be able to avoid casting to a list before doing so then. I'll switch to np.array's, test, and push a new commit.

**Comment by mhasself** [comment]
@BrianJKoopman Is this still an issue?

**Comment by BrianJKoopman** [comment]
No, since I had to cast the array in question to a list anyway (this was for proper encoding for when data was getting passed around by sisock) I did it in the code I was working on. Sorry for not following up with the np.array change, would we still prefer that over `spt3g.core.DoubleVector`?

**Comment by mhasself** [comment]
Ahh... sorry I was reading the code wrong.  Yes, please, np.array.  This is basically a bug-fix; the docstring already claims it will return an array.

**Comment by BrianJKoopman** [comment]
Switched to numpy arrays. Wrote a simple test case for verifying the type too. While simple, I hope it'll form the basis for other tests for `hk.getdata.py`.

**Pull request merged**
