### PR TITLE
created g3 reader

### PR DESCRIPTION
**Pull request by laurensaunders**
New g3 reader in python package. Current functionality for reading SMuRF g3 data to an array. (Same as smurf_g3_reader from socs)

### CODE REVIEW

**Comment by nwhitehorn** [comment]
Do you want to structure this in terms of files? If you do it in terms of streams, you could do the processing on live data. G3File is really intended only for use in interactive sessions.

**Comment by mhasself** [comment]
> Do you want to structure this in terms of files? If you do it in terms of streams, you could do the processing on live data. G3File is really intended only for use in interactive sessions.

Yes; this interface is targeting interactive / off-line data analysis.

**Comment by nwhitehorn** [comment]
"Offline" is not quite the same as "interactive" -- there are some other benefits you get from the streaming mode (handling multiple files, parallel IO, etc.). But the requirement drops a bit.

**Comment by BrianJKoopman** [comment]
Works now on recent files, merging!

**Pull request merged**
