### PR TITLE
Add from Mask option for RangesMatrix

### PR DESCRIPTION
**Pull request by kmharrington**
@mhasself  You mentioned there was a larger PR with ranges features. I don't know if you were adding this one but it would help with creating flags.

### CODE REVIEW

**Review by mhasself — APPROVED** [review]
Sorry; just saw the comment but I didn't realize it was a PR.  Looks fine, and I won't hold it up.

But it should have a docstring.

Annnnnddddd... RangesMatrix has important higher dimensional applications -- I regularly use ones with shape, e.g., (4, 1000, 123888).  It would be cool if this function checked len(shape), and recursed to RangesMatrix.from_mask until len(shape) == 2.

**Comment by mhasself** [comment]
> Annnnnddddd... RangesMatrix has important higher dimensional applications -- I regularly use ones with shape, e.g., (4, 1000, 123888). It would be cool if this function checked len(shape), and recursed to RangesMatrix.from_mask until len(shape) == 2.

And the convention I adopted with .full, .zeros, .ones (PR imminent) is that if len(shape) == 1, then it returns a simple Ranges object, instead of like crashing or whatever.

**Comment by kmharrington** [comment]
Does this make the dimensions as expected?

**Review by mhasself — APPROVED** [review]
Looks good.  I assume you tested that it at least doesn't crash on masks of 1, 2, 3d.  I'll have a unit test for the Ranges stuff soon.

Couple style notes:

(a) please leave whitespace around comparison operators such as  == and >.

(b) Note the following are equivalent:
```
 [some_func(items[i]) for i in range(len(items))]
 [some_func(item) for item in items]
```
I think the second form is to be preferred.  It does indeed work as hoped for ndarrays (iterating over the left-most dimension).

**Pull request merged**
